openapi: 3.0.0
info:
  title: Reqres API Demo
  version: 1.0.0
servers:
  - url: https://reqres.in/api
paths:
  /login:
    post:
      operationId: login
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /users:
    get:
      operationId: listUsers
      summary: List users
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
